#!/usr/bin/env sh
# Installs the `sto` command into this machine's shell. The Linux/macOS twin of
# install_sto_cli.ps1. Idempotent: re-run it after moving the repo and the next
# terminal picks up the new path.
#
# Windows needed a function per PowerShell profile because $PROFILE is a
# different file in each host. Here the shells disagree about syntax instead of
# about location, so the repo path lives in ONE executable — ~/.local/bin/sto —
# and every shell only needs that directory on PATH. bash, zsh and fish get the
# same three-line block; moving the repo rewrites the launcher and leaves the
# rc files untouched.
set -eu

START='# >>> STO CLI >>>'
END='# <<< STO CLI <<<'

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo=$(CDPATH= cd -- "$script_dir/.." && pwd)
bin_dir="$HOME/.local/bin"
launcher="$bin_dir/sto"

# A path with a quote in it would end the string and run as code.
repo_q=$(printf '%s' "$repo" | sed "s/'/'\\\\''/g")

command -v python3 >/dev/null 2>&1 || command -v python >/dev/null 2>&1 || \
    echo "[warn] no python on PATH: sto will not run until you install it" >&2

# ── the launcher: the only file that knows where the repo is ──

mkdir -p "$bin_dir"
cat > "$launcher" <<EOF
#!/usr/bin/env sh
# Generated by $repo_q/scripts/install_sto_cli.sh — edits here are overwritten.
STO_REPO='$repo_q'

if [ -n "\${STO_PYTHON:-}" ]; then
    py=\$STO_PYTHON
elif command -v python3 >/dev/null 2>&1; then
    py=python3
elif command -v python >/dev/null 2>&1; then
    py=python
else
    echo "sto: python is missing — https://www.python.org/downloads/" >&2
    exit 127
fi

# bare \`sto\` means \`sto status\`, the same as on Windows.
[ "\$#" -eq 0 ] && set -- status
exec "\$py" "\$STO_REPO/scripts/cli.py" "\$@"
EOF
chmod +x "$launcher"
echo "sto CLI installed at $launcher (repo: $repo)"

# ── PATH: the same guarded block in every shell that could open ──

posix_block="$START
# braingent-sto: \$HOME/.local/bin is where the \`sto\` launcher lives.
case \":\$PATH:\" in
    *\":\$HOME/.local/bin:\"*) ;;
    *) PATH=\"\$HOME/.local/bin:\$PATH\" ;;
esac
export PATH
$END"

fish_block="$START
# braingent-sto: \$HOME/.local/bin is where the \`sto\` launcher lives.
if not contains -- \$HOME/.local/bin \$PATH
    set -gx PATH \$HOME/.local/bin \$PATH
end
$END"

install_block() {
    target=$1
    block=$2
    mkdir -p "$(dirname -- "$target")"
    [ -f "$target" ] || : > "$target"

    # Drop the old block if it is there, leave the rest of the rc intact.
    stripped=$(awk -v s="$START" -v e="$END" '
        index($0, s) { skip = 1 }
        !skip        { print }
        index($0, e) { skip = 0 }
    ' "$target" | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba')

    if [ -n "$stripped" ]; then
        new="$stripped

$block"
    else
        new="$block"
    fi

    # `set -e` would take an unchanged file for a failure, so no `&& return`.
    if [ "$new" != "$(cat "$target")" ]; then
        printf '%s\n' "$new" > "$target"
        echo "PATH block written to $target"
    fi
}

# Written for every shell that exists on the machine, not just the one running
# this: there is no telling which terminal you will open next.
if command -v bash >/dev/null 2>&1 || [ -f "$HOME/.bashrc" ]; then
    install_block "$HOME/.bashrc" "$posix_block"
fi
if command -v zsh >/dev/null 2>&1 || [ -f "${ZDOTDIR:-$HOME}/.zshrc" ]; then
    install_block "${ZDOTDIR:-$HOME}/.zshrc" "$posix_block"
fi
fish_config="${XDG_CONFIG_HOME:-$HOME/.config}/fish/config.fish"
if command -v fish >/dev/null 2>&1 || [ -f "$fish_config" ]; then
    install_block "$fish_config" "$fish_block"
fi

case ":$PATH:" in
    *":$bin_dir:"*) ;;
    *) echo "open a new terminal (or add $bin_dir to PATH) and \`sto\` is there" ;;
esac
